services:
  pixel-ate-it:
    image: ghcr.io/josias-r/pixel-ate-it:v0.0.18
    container_name: pixel-ate-it
    restart: unless-stopped
    ports:
    #   # Expose Nginx serving the static frontend - not needed if using reverse proxy
    #   - "8080:80"
      
      # Expose the Rust WebTransport server (UDP is required) - reverse proxy tricky, so port exposing instead due to certificates generated/used for WebTransport
      - "3939:3000/udp"
      # Expose the WebSocket server (TCP)
      - "3940:3001/tcp"
    environment:
      # Ensure the Rust WebTransport port matches the exposed UDP port
      - PORT=3000
      # Ensure the Rust WebSocket port matches the exposed TCP port
      - WS_PORT=3001
      # - PUBLIC_WT_URL=https://pixel-ate-it.example.com:3939/
      # - PUBLIC_WS_URL=wss://pixel-ate-it.example.com:3940/
